### ISSUE TITLE
Console warning on Blender 3.6.4 while using False Color

### ISSUE THREAD

**Issue by Joegenco** [EaryChow/AgX#3]
Blender Console warning:

[OpenColorIO Warning]: Interpolation specified by FileTransform 'tetrahedral' is not allowed with the given file: 'AgX_False_Color.spi1d'.

Setting the interpolation to linear fixes it.
        - !<FileTransform> {src: AgX_False_Color.spi1d, interpolation: linear}

Not sure if tetrahedral is needed since its not needed to have banding presicion with falsecolor.

**Comment by EaryChow** [comment]
Hmm, I think it was "best" once, and OCIO would just select the best one available, which is probably linear. Then there was a commit to change all "best" to "tetrahedral", that's why the error. Not a big deal though.

**Comment by EaryChow** [comment]
Fixed
