### ISSUE TITLE
Should I check automatic (recommended)? This seems to show ace2065-1 instead of Agx. I'm setting up the blender octane color space.

### ISSUE THREAD

**Issue by Jackbrobeep** [EaryChow/AgX#6]
![image](https://github.com/EaryChow/AgX/assets/136829587/01039f74-62f1-4267-a0d8-0592ab25e25a)
![image](https://github.com/EaryChow/AgX/assets/136829587/d3262c51-06e0-46e1-84e2-73993a0a851b)
![image](https://github.com/EaryChow/AgX/assets/136829587/fdf1ac7c-9a05-48f9-98fe-5862dee1982c)

**Comment by EaryChow** [comment]
The intermediate colorspace is basically an anchor point between two coordinate systems.  

Like if I define the ground floor of a building to be floor 0, John defines the ground floor to be floor 1, when I send him a message that I will be waiting for him on floor 3, I will need to specify a common intermediate conversion. For example, let's say there is a platform reaching out of the building on my definition of floor 5, on John's definition of floor 6, and we previously agreed to set the platform as floor alpha, I will then send him "I am waiting for you at alpha minus 2 floor." 

The same goes with Octane, it seems to have its own internal RGB working space that gets converted to spectra to do spectral rendering, and ultimately converted back to RGB for RGB related calculations, but the RGB working space is not exposed, I don't see they mention it anywhere, I think they intentionally kept it in a blackbox. The intermediate colorspace is basically, "before Octane communiates with OCIO, they want to establish the common platform that reaches out." 

I am not very sure about the Automatic option, to me, it seems to try to look for the naming of OCIO colorspaces, if the naming is a bit different from its assumption, I am afraid it doesn't automatically recognize. Using manual is more secure in that you can make sure that they are referring to the same space as common ground. 

If manual option doesn't work, could be a bug on their end. Just report it.

**Comment by Jackbrobeep** [comment]
Thank you very much for your reply, I will try it!

EaryChow ***@***.***> 于2024年1月22日周一 21:54写道：
