### ISSUE TITLE
Incorrect matrices?

### ISSUE THREAD

**Issue by jkarow** [EaryChow/AgX#8]
Hello.
Where do all your XYZ_to_RGB matrices origin from?

They don't seem to match other official publications like e.g. on https://colour.readthedocs.io/en/develop/index.html or on https://haraldbrendel.com/colorspacecalculator.html.

And for example the matrix in the Colorspace transform defining Linear Rec.709 for the first few digits is pretty close to the one from XYZ E to Rec709. But you already convert from E to D65 via xyz_E_to_D65.spimtx before applying that.

What's up with that?

**Comment by jkarow** [comment]
colour lists this:
```
colour.models.RGB_COLOURSPACE_BT709
RGB_Colourspace('ITU-R` BT.709',
                [[ 0.64,  0.33],
                 [ 0.3 ,  0.6 ],
                 [ 0.15,  0.06]],
                [ 0.3127,  0.329 ],
                'D65',
                [[ 0.4123908 ,  0.35758434,  0.18048079],
                 [ 0.21263901,  0.71516868,  0.07219232],
                 [ 0.01933082,  0.11919478,  0.95053215]],
                [[ 3.24096994, -1.53738318, -0.49861076],
                 [-0.96924364,  1.8759675 ,  0.04155506],
                 [ 0.05563008, -0.20397696,  1.05697151]],
                oetf_BT709,
                oetf_inverse_BT709,
                False,
                False)
```


Harald Brendels Color Space Calculator this for CIE XYZ E to Rec.709:
```
 3.240970 -1.537383 -0.498611
-0.969244  1.875968  0.041555
 0.055630 -0.203977  1.056972
```

**Comment by EaryChow** [comment]
Related info here: https://projects.blender.org/blender/blender/issues/115562#issuecomment-1075996

The conlcusion I arrived to was :
> All I get from this is that, the D65 coordinate doesn't have a single ground-truth value, it depends on the method they calculated it, as well as some different way of rounding different values in different steps that they do.

Therefore I wouldn't say the matrices to be "incorrect", it's just different because of different rounding values etc. in different steps.
